// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const SharedSecretsSchema = z.object({
  id: z.string().uuid(),
  jwk: z.unknown(),
  encryptedSecret: z.string().nullable().optional(),
  expiresAt: z.date(),
  userId: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TSharedSecrets = z.infer<typeof SharedSecretsSchema>;
export type TSharedSecretsInsert = Omit<z.input<typeof SharedSecretsSchema>, TImmutableDBKeys>;
export type TSharedSecretsUpdate = Partial<Omit<z.input<typeof SharedSecretsSchema>, TImmutableDBKeys>>;
